### ISSUE TITLE
Include Pimp My Log

### ISSUE THREAD

**Issue by mikebell** [geerlingguy/drupal-vm#49]
http://pimpmylog.com/

It's a php log interface for your system, it can be installed via composer and is fairly light weight.

## Tasks

- [x] Create new [`geerlingguy.pimpmylog`](https://github.com/geerlingguy/ansible-role-pimpmylog) role.
- [x] Use role to install Pimp my Log in Drupal VM default configuration.
- [x] Add [wiki page](https://github.com/geerlingguy/drupal-vm/wiki/View-Logs-with-Pimp-my-Log) explaining Pimp my Log configuration.
- [x] Update documentation on www.drupalvm.com
- [x] Update README.md with information about Pimp my Log.

**Comment by geerlingguy** [comment]
Looks reasonable; I'll create a role for it and then add it as an optional install.

**Comment by geerlingguy** [comment]
Another option: https://github.com/mthenw/frontail (but this requires node.js to also be installed... slippery slope there!).

**Comment by mikebell** [comment]
There are some really nice logging systems out there but most of them require extra stacks to run on probably best to keep things simple.

**Comment by mikecrittenden** [comment]
Just dropping by to note that in my mind this and xhgui are the only two things that Vlad has over drupal-vm at this point.

**Comment by geerlingguy** [comment]
- [x] Create new `geerlingguy.pimpmylog` role.
- [x] Use role to install Pimp my Log in Drupal VM default configuration.
- [ ] Add wiki page for configuring Pimp my Log
- [ ] Update documentation on www.drupalvm.com
- [ ] Update README.md with information about Pimp my Log

**Comment by geerlingguy** [comment]
Fixed!
